[mysql]
host = "127.0.0.1"
port = 3306
database = "tictok"
username = "root"
password = "123456"
charset = "utf8mb4"
parse_time = true
loc = "Local"

[mysqltest]
host = "127.0.0.1"
port = 3306
database = "tictoktest"
username = "root"
password = "123456"
charset = "utf8mb4"
parse_time = true
loc = "Local"

[path]
static_source_path = "http://10.200.79.164:8080/static/"
ffmpeg_path = "D:/DKU/byteCamp/Tiny-TicTok/ffmpeg/ffmpeg-2023-02-02-git-7d49fef8b4-essentials_build/ffmpeg-2023-02-02-git-7d49fef8b4-essentials_build/bin/ffmpeg.exe"